<?php

namespace Database\Seeders;

use App\Models\Student;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class StudentBulkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $studentsData = [
            [
                'email' => 'alsyazia2013@gmail.com',
                'name' => 'Alsyazia Fidelya Arnessa',
                'school_name' => 'SMPN 1 kota Sukabumi',
                'phone' => '+62 896-4636-4957',
                'guardian_phone' => '+62 896-4636-4957',
                'nisn' => '1111265',
            ],
            [
                'email' => 'syifapujisuci1987@gmail.com',
                'name' => 'Fakhira Wahda Niksyi',
                'school_name' => 'Mts Ma Pusat Menes',
                'phone' => '081318999698',
                'guardian_phone' => '081394466996',
                'nisn' => '1111266',
            ],
            [
                'email' => 'rayyan.maesa11@gmail.com',
                'name' => 'Rayyan Maesa Abdul Rachman',
                'school_name' => 'SMPI AL AZHAR 16 CIKARANG',
                'phone' => '087762436628',
                'guardian_phone' => '087889145951',
                'nisn' => '1111267',
            ],
            [
                'email' => 'rayyan.maesa11.alt@gmail.com',
                'name' => 'Rayyan Maesa Abdul Rachman (2)',
                'school_name' => 'SMPI AL AZHAR 16 CIKARANG',
                'phone' => '087762436628',
                'guardian_phone' => '087889145951',
                'nisn' => '1111268',
            ],
            [
                'email' => 'ziyasadra14@gmail.com',
                'name' => 'Fauziya Khairunisadra',
                'school_name' => 'SMP Islam Al Falah Jambi',
                'phone' => '0821-7990-5891',
                'guardian_phone' => '0813-7353-6600',
                'nisn' => '1111269',
            ],
            [
                'email' => 'mdafaramadhan9@gmail.com',
                'name' => 'Muhammad Daffa Ramadhan',
                'school_name' => 'SMP ISLAM AL FALAH JAMBI',
                'phone' => '083151823531',
                'guardian_phone' => '082121259855',
                'nisn' => '1111270',
            ],
            [
                'email' => 'azzammubarak1225@gmail.com',
                'name' => 'Azzam Hulawi Azfar',
                'school_name' => 'MtsN 2 Kota Jambi',
                'phone' => '082375122682',
                'guardian_phone' => '081322604243',
                'nisn' => '1111271',
            ],
            [
                'email' => 'astilaputri470@gmail.com',
                'name' => 'Astila Putri Syahnia',
                'school_name' => 'MTsN 1 Merangin',
                'phone' => '0812-7899-7067',
                'guardian_phone' => '0813-6680-8688',
                'nisn' => '1111272',
            ],
            [
                'email' => 'radityaapratama20@gmail.com',
                'name' => 'Raditya Pratama',
                'school_name' => 'MTsN 2 Kota Jambi',
                'phone' => '0822 7986 9769',
                'guardian_phone' => '0821 8215 6135',
                'nisn' => '1111273',
            ],
            [
                'email' => 'battousai786@yahoo.com',
                'name' => 'Zahir Mirza',
                'school_name' => 'SMP Pupuk Kujang Cikampek',
                'phone' => '081282667047',
                'guardian_phone' => '081281618863',
                'nisn' => '1111274',
            ],
            [
                'email' => 'sdumayanti@gmail.com',
                'name' => 'Joanna Alicia Bernessa',
                'school_name' => 'SMP Pupuk Kujang Cikampek',
                'phone' => '+62 857-1942-0311',
                'guardian_phone' => '085715470124',
                'nisn' => '1111275',
            ],
            [
                'email' => 'kamalfirdaus88@gmail.com',
                'name' => 'Tsabita maritza',
                'school_name' => 'Mts nururodiyah',
                'phone' => '081368380263',
                'guardian_phone' => '081366909499',
                'nisn' => '1111276',
            ],
            [
                'email' => 'nurricayanti@gmail.com',
                'name' => 'Kinara faiqa asiah',
                'school_name' => 'SMP IT Nurul Ilmi 2 Jambi',
                'phone' => '+62 822-9361-8394',
                'guardian_phone' => '082268297575',
                'nisn' => '1111277',
            ],
            [
                'email' => 'lidia.natalia55@gmail.com',
                'name' => 'YUDIA ADELYA UTAMI',
                'school_name' => 'SMPQ CENDIKIA RABBANI KABUPATEN TEBO PROVINSI JAMBI',
                'phone' => '089630864204',
                'guardian_phone' => '085294122646',
                'nisn' => '1111278',
            ],
            [
                'email' => 'rizasulfianna@gmail.com',
                'name' => 'KHAIRUNNISA FADHILAH',
                'school_name' => 'MTsN 1 PEKANBARU',
                'phone' => '08136702012',
                'guardian_phone' => '081266620935',
                'nisn' => '1111279',
            ],
            [
                'email' => 'zulfanailahlabibah@gmail.com',
                'name' => 'Zulfa Nailah Labibah',
                'school_name' => 'SMP IT Nurul Ilmi 2 Jambi',
                'phone' => '082245235897',
                'guardian_phone' => '082278515955',
                'nisn' => '1111280',
            ],
            [
                'email' => 'anti71008@gmail.com',
                'name' => 'KAYLA LALITA PUTRI',
                'school_name' => 'Smp candikia rabbani kab tebo',
                'phone' => '082184606480',
                'guardian_phone' => '082184605811',
                'nisn' => '1111281',
            ],
            [
                'email' => 'anggrainidesi079@gmail.com',
                'name' => 'Ahda Sabila',
                'school_name' => 'SMP Qur\'an Cendekia Rabbani',
                'phone' => '082371413882',
                'guardian_phone' => '085272088774',
                'nisn' => '1111282',
            ],
            [
                'email' => 'zahraazkia414@gmail.com',
                'name' => 'Azkia Az-zahra Ashari',
                'school_name' => 'Mts Putri As\'ad',
                'phone' => '082372828522',
                'guardian_phone' => '081366674006',
                'nisn' => '1111283',
            ],
            [
                'email' => 'azkadinaputri.raisha@gmail.com',
                'name' => 'Raisha Azkadina Putri',
                'school_name' => 'SMP AHMAD DAHLAN KOTA JAMBI',
                'phone' => '89505861307',
                'guardian_phone' => '+62 852-6669-4068',
                'nisn' => '1111284',
            ],
            [
                'email' => 'reginamaher13@gmail.com',
                'name' => 'regina grisalda',
                'school_name' => 'smpit nurul ilmi 2',
                'phone' => '083870334242',
                'guardian_phone' => '085357697249',
                'nisn' => '1111285',
            ],
            [
                'email' => 'bhiandra09@gmail.com',
                'name' => 'bhiandra muharrami r',
                'school_name' => 'nurul ilmi 2',
                'phone' => '081366163633',
                'guardian_phone' => '082217460895',
                'nisn' => '1111286',
            ],
            [
                'email' => 'nurarifaqalbiya99@gmail.com',
                'name' => 'Nur Arifa Qalbiya',
                'school_name' => 'SMPIT Nurul Ilmi 2 Kota Jambi',
                'phone' => '+6281933904905',
                'guardian_phone' => '+62 811-7497-956',
                'nisn' => '1111287',
            ],
            [
                'email' => 'assyifabko@gmail.com',
                'name' => 'Assyifa Khumairoh',
                'school_name' => 'MTsN 8 BATANG HARI',
                'phone' => '083166113156',
                'guardian_phone' => '085381902600',
                'nisn' => '1111288',
            ],
            [
                'email' => 'nadya.zamzam@gmail.com',
                'name' => 'Aurora Zadeeya',
                'school_name' => 'SMPN 4 TANGERANG SELATAN',
                'phone' => '083849316731',
                'guardian_phone' => '082210001081',
                'nisn' => '1111289',
            ],
            [
                'email' => 'fadhielnawwafmahendrafa@gmail.com',
                'name' => 'Fadhiel Nawwaf Mahendrafa',
                'school_name' => 'SMP Pupuk Kujang',
                'phone' => '081250243081',
                'guardian_phone' => '082125156559',
                'nisn' => '1111290',
            ],
            [
                'email' => 'hanafidzaky35@gmail.com',
                'name' => 'M.Dzaky zdakwan hanafi',
                'school_name' => 'MTs NURURRODHIYAH',
                'phone' => 'O89679445428',
                'guardian_phone' => '0811744075',
                'nisn' => '1111291',
            ],
            [
                'email' => 'ibrahim210612@gmail.com',
                'name' => 'Ibrahim Yusuf',
                'school_name' => 'MTsN 1 andalan Pekanbaru',
                'phone' => '081276078883',
                'guardian_phone' => '081365348883',
                'nisn' => '1111292',
            ],
            [
                'email' => 'faizzarif8@gmail.com',
                'name' => 'Faiz Zarif',
                'school_name' => 'MTsN1 pekanbaru',
                'phone' => '082173566401',
                'guardian_phone' => '08127640356',
                'nisn' => '1111293',
            ],
            [
                'email' => 'fadel.rauhillah@gmail.com',
                'name' => 'Muhammad Fadel Rauhillah',
                'school_name' => 'MtsN 1 Pekanbaru',
                'phone' => '0821-8506-1174',
                'guardian_phone' => '081381419556',
                'nisn' => '1111294',
            ],
            [
                'email' => 'floriashoffiya@gmail.com',
                'name' => 'Floria shoffiya lateefa',
                'school_name' => 'Smp ahmad dahlan kota jambi',
                'phone' => '0822-7849-8199',
                'guardian_phone' => '0821-8327-7429',
                'nisn' => '1111295',
            ],
            [
                'email' => 'reniara84@gmail.com',
                'name' => 'SENANDUNG TAZKIYAH',
                'school_name' => 'Nurul Ilmu 2 kota Jambi',
                'phone' => '08137883313',
                'guardian_phone' => '082243790405',
                'nisn' => '1111296',
            ],
            [
                'email' => 'afridanajlafaiza@gmail.com',
                'name' => 'FAIZA AFRIDA NAJLA',
                'school_name' => 'MTSN 5 MAJALENGKA',
                'phone' => '+62 812-2418-1114',
                'guardian_phone' => '+62 821-1717-1368',
                'nisn' => '1111297',
            ],
            [
                'email' => 'malahayatilintang@gmail.com',
                'name' => 'Malahayati Lintang Malaikah',
                'school_name' => 'MTs Negeri 5 Cilacap',
                'phone' => '082329688492',
                'guardian_phone' => '083862286518',
                'nisn' => '1111298',
            ],
            [
                'email' => 'shiikanna757@gmail.com',
                'name' => 'FATIMAH AHDA AFIYAH',
                'school_name' => 'SMP ISLAM AL FALAH JAMBI',
                'phone' => '+62 852-6972-7101',
                'guardian_phone' => '+62 812-6238-2422',
                'nisn' => '1111299',
            ],
            [
                'email' => 'putriagustinramadani2012@gmail.com',
                'name' => 'PUTRI AGUSTIN RAMADHANI',
                'school_name' => 'MTS N 5 CILACAP',
                'phone' => '+63 851 3820 6560',
                'guardian_phone' => '+62 812 8399 1195',
                'nisn' => '1111300',
            ],
            [
                'email' => 'isan97055@gmail.com',
                'name' => 'IHSAAN FAJAR MUSTOFA',
                'school_name' => 'MTS N 5 CLP',
                'phone' => '088980001861',
                'guardian_phone' => '081391001119',
                'nisn' => '1111301',
            ],
            [
                'email' => 'vinazakiyahalvina@gmail.com',
                'name' => 'zakiyah alvina',
                'school_name' => 'sempit nurul ilmi 2 kota jambi',
                'phone' => '081223412221',
                'guardian_phone' => '081278284882',
                'nisn' => '1111302',
            ],
            [
                'email' => 'jaisyazzahra7415@gmail.com',
                'name' => 'Khaira Jaisy Azzahra',
                'school_name' => 'SMP Negeri 4 Kota Tangsel',
                'phone' => '082189004257',
                'guardian_phone' => '087733932925',
                'nisn' => '1111303',
            ],
            [
                'email' => 'senaquratulaqyun12@gmail.com',
                'name' => 'Syena Qurratul Aqyun',
                'school_name' => 'MTs N 1 Kerinci',
                'phone' => '+62 813-6158-684',
                'guardian_phone' => '+62 822-8119-2299',
                'nisn' => '1111304',
            ],
            [
                'email' => 'luthfi.ml1506@gmail.com',
                'name' => 'Luthfi Maulana',
                'school_name' => 'MTsN 1 Pekanbaru',
                'phone' => '+62 821-8028-1966',
                'guardian_phone' => '+62 852-6013-8552',
                'nisn' => '1111305',
            ],
            [
                'email' => 'rikirizky105@gmail.com',
                'name' => 'SITA KIRANA KHAIRUNNISA',
                'school_name' => 'MTS NEGERI 7 MUARA JAMBI',
                'phone' => '085377093539',
                'guardian_phone' => '082177487788',
                'nisn' => '1111306',
            ],
            [
                'email' => 'keenandaqila2609@gmail.com',
                'name' => 'Keenand Aqila Rizanuar Putra',
                'school_name' => 'MTsN 1 Kebumen',
                'phone' => '088801308131',
                'guardian_phone' => '082136442119',
                'nisn' => '1111307',
            ],
            [
                'email' => 'fathanalvarozar@gmail.com',
                'name' => 'Fathan alvaro zar',
                'school_name' => 'smpit nurul ilmi 2 kota jambi',
                'phone' => '085609509875',
                'guardian_phone' => '081274999912',
                'nisn' => '1111308',
            ],
            [
                'email' => 'thaniashafira.r@gmail.com',
                'name' => 'Fathaniah Shafira Rusliyadi',
                'school_name' => 'MTs Negeri 1 Kebumen',
                'phone' => '085135331942',
                'guardian_phone' => '085227160848',
                'nisn' => '1111309',
            ],
            [
                'email' => 'inianasipatau@gmail.com',
                'name' => 'Syifa Nur Faisatun Putri',
                'school_name' => 'SMP IT NURIL ILMI',
                'phone' => '081374190117',
                'guardian_phone' => '085377082811',
                'nisn' => '1111310',
            ],
            [
                'email' => 'faeyzarahman4@gmail.com',
                'name' => 'Faeyza Aulia Syazani',
                'school_name' => 'MTsN 1 Kebumen',
                'phone' => '089606700661',
                'guardian_phone' => '087719751944',
                'nisn' => '1111311',
            ],
            [
                'email' => 'waminwahyudi@gmail.com',
                'name' => 'caca ajeng ayu sekar kinanti',
                'school_name' => 'mts N7',
                'phone' => '083171797557',
                'guardian_phone' => '082380970354',
                'nisn' => '1111312',
            ],
            [
                'email' => 'husnaafifah911@gmail.com',
                'name' => 'Husna Afifah',
                'school_name' => 'MTs Negeri 7 Muaro Jambi',
                'phone' => '085215066045',
                'guardian_phone' => '085267173917',
                'nisn' => '1111313',
            ],
            [
                'email' => 'hafizahrahmatika78@gmail.com',
                'name' => 'HAFIZAH RAHMATIKA ILMAH',
                'school_name' => 'MTSN 3 KUANSING',
                'phone' => '082261427387',
                'guardian_phone' => '081266407516',
                'nisn' => '1111314',
            ],
            [
                'email' => 'alyaageng11@gmail.com',
                'name' => 'Alya Ageng Pramidita',
                'school_name' => 'MTs N 1 Kebumen',
                'phone' => '085641808423',
                'guardian_phone' => '085842630482',
                'nisn' => '1111315',
            ],
        ];

        foreach ($studentsData as $item) {
            $user = User::updateOrCreate(
                ['email' => $item['email']],
                [
                    'name' => $item['name'],
                    'password' => Hash::make($item['nisn']),
                    'role' => 'student',
                ]
            );

            Student::updateOrCreate(
                ['user_id' => $user->id],
                [
                    'nisn' => $item['nisn'],
                    'school_name' => $item['school_name'],
                    'phone' => $item['phone'],
                    'guardian_name' => $item['guardian_phone'],
                    'class_name' => 'Reguler',
                    'status' => 'active',
                ]
            );
        }
    }
}
