<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $student ? 'Edit' : 'Tambah' }} Mahasiswa | Cakrawala</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#F8FAFC] pb-28 font-sans text-slate-800 antialiased">
@include('components.headerAdmin')
<main class="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-12"><div class="mb-6"><a href="{{ route('admin.siswa.index') }}" class="text-sm font-bold text-indigo-600">&larr; Kembali ke mahasiswa</a><h1 class="mt-3 text-2xl font-black text-slate-900">{{ $student ? 'Edit mahasiswa' : 'Tambah mahasiswa' }}</h1></div>
@if ($errors->any())<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $student ? route('admin.siswa.update', $student) : route('admin.siswa.store') }}" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">@csrf @if ($student) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2"><label class="text-sm font-bold text-slate-700">Nama lengkap<input name="name" value="{{ old('name', $student?->user?->name) }}" required class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-bold text-slate-700">Email<input type="email" name="email" value="{{ old('email', $student?->user?->email) }}" required class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-bold text-slate-700">NISN<input name="nisn" value="{{ old('nisn', $student?->nisn) }}" required class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-bold text-slate-700">Kelas<input name="class_name" value="{{ old('class_name', $student?->class_name) }}" required class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-bold text-slate-700">No. telepon<input name="phone" value="{{ old('phone', $student?->phone) }}" class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-bold text-slate-700">Status<select name="status" class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"><option value="active" @selected(old('status', $student?->status ?? 'active') === 'active')>Aktif</option><option value="inactive" @selected(old('status', $student?->status) === 'inactive')>Tidak aktif</option></select></label><label class="text-sm font-bold text-slate-700 sm:col-span-2">Password {{ $student ? '(kosongkan jika tidak diubah)' : '' }}<input type="password" name="password" {{ $student ? '' : 'required' }} class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"></label><label class="text-sm font-bold text-slate-700 sm:col-span-2">Konfirmasi password<input type="password" name="password_confirmation" {{ $student ? '' : 'required' }} class="mt-2 w-full rounded-xl border-slate-200 px-3 py-2.5 text-sm"></label></div>
<div class="flex justify-end"><button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white hover:bg-indigo-700">Simpan data</button></div></form></main>@include('components.footerMobile_admin')</body></html>
