<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Materi Belajar | Cakrawala</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#F8FAFC] pb-24 font-sans text-slate-800 antialiased">
@include('components.hiderSiswa')
<main class="mx-auto max-w-4xl space-y-6 px-4 py-8 sm:px-6 lg:px-12"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-indigo-500">Ruang belajar</p><h1 class="mt-1 text-2xl font-black tracking-tight text-slate-900">Materi saya</h1><p class="mt-2 text-sm text-slate-500">Materi yang sudah diterbitkan oleh guru untuk kamu pelajari.</p></div>
<section class="space-y-3"><h2 class="text-sm font-black text-slate-900">Materi pembelajaran</h2>@forelse ($materials as $material)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><span class="rounded-lg bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-600">{{ $material->subject }}</span><h2 class="mt-3 text-lg font-black text-slate-900">{{ $material->title }}</h2><p class="mt-2 text-sm leading-relaxed text-slate-500">{{ $material->summary ?: 'Tidak ada ringkasan materi.' }}</p></div><span class="shrink-0 text-xs font-semibold text-slate-400">{{ $material->published_at?->format('d M Y') }}</span></div><div class="mt-4 flex flex-wrap gap-3 border-t border-slate-100 pt-3 text-xs font-semibold text-slate-500">Dibuat oleh {{ $material->teacher->user->name }} @if ($material->video_url)<a href="{{ $material->video_url }}" target="_blank" rel="noreferrer" class="text-indigo-600 hover:underline">Tonton video</a>@endif @if ($material->attachment_path)<a href="{{ Storage::disk('public')->url($material->attachment_path) }}" target="_blank" rel="noreferrer" class="text-rose-600 hover:underline">Unduh modul</a>@endif</div></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white px-5 py-12 text-center text-sm text-slate-400">Belum ada materi yang diterbitkan.</div>@endforelse</section>
<section class="space-y-3"><h2 class="text-sm font-black text-slate-900">Tugas dari guru</h2>@forelse ($assignments as $assignment)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span class="rounded-lg bg-amber-50 px-3 py-1 text-xs font-bold text-amber-600">{{ $assignment->classroom->name }}</span><h2 class="mt-3 text-lg font-black text-slate-900">{{ $assignment->title }}</h2><p class="mt-2 text-sm leading-relaxed text-slate-500">{{ $assignment->instructions }}</p><p class="mt-3 text-xs font-semibold text-slate-400">Nilai maksimal {{ $assignment->points }} @if ($assignment->due_at) · Tenggat {{ $assignment->due_at->format('d M Y H:i') }}@endif</p></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white px-5 py-8 text-center text-sm text-slate-400">Belum ada tugas yang diterbitkan.</div>@endforelse</section>
<section class="space-y-3"><h2 class="text-sm font-black text-slate-900">Kuis dari guru</h2>@forelse ($quizzes as $quiz)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span class="rounded-lg bg-sky-50 px-3 py-1 text-xs font-bold text-sky-600">{{ $quiz->classroom->name }}</span><h2 class="mt-3 text-lg font-black text-slate-900">{{ $quiz->title }}</h2><p class="mt-2 text-sm text-slate-500">{{ $quiz->question_count }} soal · {{ $quiz->duration_minutes }} menit · KKM {{ $quiz->passing_score }}</p></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white px-5 py-8 text-center text-sm text-slate-400">Belum ada kuis yang diterbitkan.</div>@endforelse</section></main>
@include('components.footerSiswa')
@include('components.footerMobile_siswa')
</body></html>
