<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $classroom->name }} | Cakrawala</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#F8FAFC] pb-24 font-sans text-slate-800 antialiased">
@include('components.hiderSiswa')
<main class="mx-auto max-w-4xl space-y-6 px-4 py-8 sm:px-6 lg:px-12"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-indigo-500">Ruang kelas</p><h1 class="mt-1 text-2xl font-black text-slate-900">{{ $classroom->name }}</h1><p class="mt-2 text-sm text-slate-500">{{ $classroom->subject }} · {{ $classroom->grade_level }} · Guru: {{ $classroom->teacher?->user?->name ?? 'Guru' }}</p></div>
<section class="space-y-3"><h2 class="text-sm font-black text-slate-900">Materi pembelajaran</h2>@forelse ($materials as $material)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span class="rounded-lg bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-600">{{ $material->subject }}</span><h3 class="mt-3 text-lg font-black text-slate-900">{{ $material->title }}</h3><p class="mt-2 text-sm leading-relaxed text-slate-500">{{ $material->summary ?: 'Tidak ada ringkasan materi.' }}</p><div class="mt-4 flex flex-wrap gap-3 border-t border-slate-100 pt-3 text-xs font-bold">@if ($material->video_url)<a href="{{ $material->video_url }}" target="_blank" class="text-indigo-600 hover:underline">Tonton video</a>@endif @if ($material->attachment_path)<a href="{{ Storage::disk('public')->url($material->attachment_path) }}" target="_blank" class="text-rose-600 hover:underline">Unduh modul</a>@endif</div></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">Belum ada materi di kelas ini.</div>@endforelse</section>
<section class="space-y-3"><h2 class="text-sm font-black text-slate-900">Tugas dan kuis</h2>@forelse ($assignments as $assignment)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span class="rounded-lg bg-amber-50 px-3 py-1 text-xs font-bold text-amber-600">Tugas</span><h3 class="mt-3 text-lg font-black text-slate-900">{{ $assignment->title }}</h3><p class="mt-2 text-sm text-slate-500">{{ $assignment->instructions }}</p><p class="mt-3 text-xs font-semibold text-slate-400">Nilai maksimal {{ $assignment->points }}{{ $assignment->due_at ? ' · Tenggat '.$assignment->due_at->format('d M Y H:i') : '' }}</p></article>@empty<p class="text-sm text-slate-400">Belum ada tugas yang diterbitkan.</p>@endforelse @foreach ($quizzes as $quiz)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span class="rounded-lg bg-sky-50 px-3 py-1 text-xs font-bold text-sky-600">Kuis</span><h3 class="mt-3 text-lg font-black text-slate-900">{{ $quiz->title }}</h3><p class="mt-2 text-sm text-slate-500">{{ $quiz->question_count }} soal · {{ $quiz->duration_minutes }} menit · KKM {{ $quiz->passing_score }}</p></article>@endforeach</section></main>
@include('components.footerSiswa')
@include('components.footerMobile_siswa')
</body></html>
