<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Tugas dan Kuis | Cakrawala</title><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#F8FAFC] pb-24 font-sans text-slate-800 antialiased">
@include('components.hiderSiswa')
<main class="mx-auto max-w-4xl space-y-6 px-4 py-8 sm:px-6 lg:px-12"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-indigo-500">Ruang evaluasi</p><h1 class="mt-1 text-2xl font-black tracking-tight text-slate-900">Tugas dan Kuis</h1><p class="mt-2 text-sm text-slate-500">Evaluasi yang diterbitkan guru untuk kelasmu.</p></div>
<section id="tugas" class="scroll-mt-24 space-y-3"><h2 class="text-sm font-black text-slate-900">Tugas aktif</h2>@forelse ($assignments as $assignment)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><span class="rounded-lg bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-600">{{ $assignment->classroom->name }}</span><h3 class="mt-3 text-lg font-black text-slate-900">{{ $assignment->title }}</h3><p class="mt-2 text-sm leading-relaxed text-slate-500">{{ $assignment->instructions }}</p></div><span class="shrink-0 text-xs font-semibold text-slate-400">{{ $assignment->due_at?->format('d M Y H:i') ?? 'Tanpa tenggat' }}</span></div><div class="mt-4 border-t border-slate-100 pt-3 text-xs font-semibold text-slate-500">Nilai maksimal {{ $assignment->points }}</div></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white px-5 py-10 text-center text-sm text-slate-400">Belum ada tugas yang diterbitkan.</div>@endforelse</section>
<section id="kuis" class="scroll-mt-24 space-y-3"><h2 class="text-sm font-black text-slate-900">Kuis evaluasi</h2>@forelse ($quizzes as $quiz)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><span class="rounded-lg bg-amber-50 px-3 py-1 text-xs font-bold text-amber-600">{{ $quiz->classroom->name }}</span><h3 class="mt-3 text-lg font-black text-slate-900">{{ $quiz->title }}</h3><p class="mt-2 text-sm text-slate-500">{{ $quiz->question_count }} soal · {{ $quiz->duration_minutes }} menit · KKM {{ $quiz->passing_score }}</p></div><span class="shrink-0 text-xs font-semibold text-slate-400">{{ $quiz->due_at?->format('d M Y H:i') ?? 'Tanpa tenggat' }}</span></div></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white px-5 py-10 text-center text-sm text-slate-400">Belum ada kuis yang diterbitkan.</div>@endforelse</section></main>
@include('components.footerSiswa')
@include('components.footerMobile_siswa')
</body></html>
